language: ruby
rvm:
- 2.0.0
env:
- DB=postgresql
before_script:
- psql -c 'create database pigbank_test' -U postgres
script:
- RAILS_ENV=test bundle exec rake --trace db:migrate
- bundle exec rspec spec
cache: bundler
deploy:
  provider: heroku
  api_key:
    secure: vEJ3oAAMG5me5R8ZTj8tO6gCrW7iugl9rZ/Mijfq5EwFNxxjTJRPhv7lDdLtBHjDXZamNgTQtDFqd3rzUw02uZ3tF65E6D+lqwziyBeGajsgIAR9eDn4j8wAQsipS8Ib6mztO2GnYMbmuNZ50aquLrJus2niNrZKdpup3kHdr0Q=
  app: pigbank
  on:
    repo: guivinicius/pigbank
  run:
    - "rake db:migrate"
