postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: pigbank_<%= Rails.env %>
  min_messages: ERROR
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *postgresql

test:
  <<: *postgresql

production:
  <<: *postgresql